CREATE TABLE users (
  id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, AUTO_INCREMENT = 2,
  username VARCHAR(16) NOT NULL UNIQUE,
  password VARCHAR(60) NOT NULL,
  fullname VARCHAR(100) NOT NULL 
);
