CREATE TABLE users (
  id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(16) NOT NULL UNIQUE,
  password VARCHAR(60) NOT NULL,
  fullname VARCHAR(50) NOT NULL 
);

CREATE TABLE history (
  id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  place VARCHAR(100) NULL,
  emergency VARCHAR(100) NULL,
  need VARCHAR(100) NULL,
  message VARCHAR(100) NULL,
  node INT(11) NOT NULL,
  cookies VARCHAR(100) NOT NULL UNIQUE,
  lati VARCHAR(20),
  lngi VARCHAR(20)
);
